[Map] Add base map composable's fundamentals (#2)
* add MapLifecycleCallbacks

* add MapEventListeners

* add MapPropertiesNode

* mod MapPropertiesNode for control-padding

* add ContentDescription to Map's Modifier

* add GetMap Extension for internal usage

* add MapUpdater to refresh status

* add MapInitialOptions

* add MapViewSettings

* remove duplicate block

* add MapInitialOptions and cleaning

* add preview-guard logic

* add gesture settings

* add dokka dependency

* add kotlin-binaryCompatibilityValidator dependency

* add gradle.properties

* mod build.gradle with configurations

* add ktlint plugin dependency

* suppress compileSdk 34

* add public visibility for api-adaptation

* add api dump and apiCheck on precommit

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -23,3 +23,14 @@ if ! git diff --name-only --cached --relative \
     printf '\nktlint check failed.\nPlease check your code before commit!\n'
   exit 1
 fi
+
+# api checking
+./gradlew apiCheck -q
+API_CHECK_EXIT_CODE=$?
+if [ $EXIT_CODE -ne 0 ]; then
+  echo "apiCheck Failed. check your api"
+
+  exit $API_CHECK_EXIT_CODE
+fi
+
+exit 0
